### ISSUE TITLE
why my display failed. 

### ISSUE THREAD

**Issue by moodsdada** [comaeio/SwishDbgExt#11]
kd> !SwishDbgExt.help
       SwishDbgExt  - Incident Response & Digital Forensics Debugging Extension
       SwishDbgExt Copyright (C) 2016 Comae Technologies FZE
       SwishDbgExt Copyright (C) 2014-2016 Matthieu Suiche (@msuiche) - http://msuiche.net

       This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
       This is free software, and you are welcome to redistribute it
       under certain conditions; type `show c' for details.
e06d7363 Exception in SwishDbgExt.help debugger extension.
      PC: 000007fe`fcf1a06d  VA: 00000000`08e5d5d0  R/W: 19930520  Parameter: 000007fe`e9590648

**Comment by AndreyBazhan** [comment]
Please, download the latest release https://github.com/comaeio/SwishDbgExt/releases/tag/v3.0.20171023.2 and https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/
